[[redirects]]
  from = "/:splat" 
  to = "/:splat"  
  status = 200   

[[redirects]]
  from = "/:splat"     
  to = "/live/:splat" 
  status = 200       

[[redirects]]
  from = "/resume"     
  to = "/live/resume.pdf" 
  status = 200       


